#update config/config.properties
#Mon Feb 10 23:05:10 GMT+08:00 2025
Debug=1
JavaCompileDir=
JavaRelative=-1
MinGWDir=D\:\\SchoolStudy\\OJ_netbeans\\OJ\\client\\MinGW\\bin
MinGWRelative=1
URLip=106.15.36.190
URLport=8080
Username=felix
isCppRelative=true
isJavaRelative=true
relativeCCompilerDir=\\MinGW\\bin
relativeCppCompilerDir=\\MinGW\\bin
